using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MEFEditor.Analyzing.Editing
{
    /// <summary>
    /// Data that can be stored in execution view. Usually there are stored
    /// source data generated by transformations.
    /// </summary>
    public abstract class ExecutionViewData
    {
        /// <summary>
        /// Is called when clone of represented data is required.
        /// </summary>
        /// <returns>Cloned data.</returns>
        protected abstract ExecutionViewData clone();

        /// <summary>
        /// Is called when view has been committed.
        /// </summary>
        protected virtual void commit()
        {
            //by default there is nothing to commit
        }
        
        /// <summary>
        /// Clones represented data.
        /// </summary>
        /// <returns>ExecutionViewData clone.</returns>
        internal ExecutionViewData Clone()
        {
            return clone();
        }

        /// <summary>
        /// Commits stored data.
        /// </summary>
        internal void Commit()
        {
            commit();
        }
    }
}
