using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Analyzing.Editing
{
    /// <summary>
    /// Data that can be stored in execution view. Usually there are stored
    /// source data generated by transformations
    /// </summary>
    public abstract class ExecutionViewData
    {
        protected abstract ExecutionViewData clone();

        protected virtual void commit()
        {
            //by default there is nothing to commit
        }


        internal ExecutionViewData Clone()
        {
            return clone();
        }

        internal void Commit()
        {
            commit();
        }
    }
}
